### ISSUE TITLE
the pdf of generating attack graph for CTI report is null

### ISSUE THREAD

**Issue by stwater20** [li-zhenyuan/Knowledge-enhanced-Attack-Graph#11]
The pdf result of running the following line of code is empty... What is the problem?
`python main.py -M attackGraphGeneration -R "./Dataset/Evaluation/Frankenstein Campaign.txt" -O ./output.pdf`

<img width="852" alt="image" src="https://user-images.githubusercontent.com/50062014/219421590-28daf3c1-581a-4bbb-811a-ed8232cba0d9.png">

Thank you very much for your help

**Comment by li-zhenyuan** [comment]
It is not null. You should zoom in for details.
Currently, the graph is not strongly connected. You can ajust the parameter in code to make them connected or use the archived version.

**Comment by stwater20** [comment]
Real...
I fell asleep

Thanks for your reply
