### ISSUE TITLE
techniqueIdentification function no pdf output file

### ISSUE THREAD

**Issue by stwater20** [li-zhenyuan/Knowledge-enhanced-Attack-Graph#12]
I use the instructions mentioned above in the readme.md.

python main.py -M techniqueIdentification -T ./templates -R "./Dataset/Evaluation/Frankenstein Campaign.txt" -O ./output2.pdf

It has generated this output2.pdf_techniques.json file, but no pdf is produced.

<img width="874" alt="image" src="https://user-images.githubusercontent.com/50062014/225539138-0a8472df-6726-4f5c-a827-45d9c2e6b919.png">

Thanks for your help

**Comment by li-zhenyuan** [comment]
Maybe you need to install graphviz to render the pdf.

**Comment by stwater20** [comment]
Thank you, I will try it later.

I found another issue: the field of ioc is "set()".

<img width="699" alt="image" src="https://user-images.githubusercontent.com/50062014/225542902-88cfcfaa-e643-4678-8332-2d9823ee96b1.png">

Please, what might be the reason?

Thank you very much

I use this command:
python main.py -M attackGraphGeneration -R "./Dataset/Evaluation/Frankenstein Campaign.txt" -O ./output.pdf

**Comment by li-zhenyuan** [comment]
Have no idea.
