### ISSUE TITLE
图中的节点怎么理解

### ISSUE THREAD

**Issue by SuoFei01** [li-zhenyuan/Knowledge-enhanced-Attack-Graph#13]
生成的攻击图中节点的意思应该怎么理解？
![image](https://user-images.githubusercontent.com/126148490/232784200-5e60c39f-4115-49ed-bdfd-cedbf96da7b2.png)
#隔开的四个字段代表什么意思？

**Comment by li-zhenyuan** [comment]
论文、代码里都有描述。
