### ISSUE TITLE
How to produce the trees for the output_techniques.

### ISSUE THREAD

**Issue by Ema-Ans** [li-zhenyuan/Knowledge-enhanced-Attack-Graph#14]
I tried installing Graphviz, but I am still not too sure how to convert the JSON output for the techniques into pdf, for the technique identification function. (It's similar to issue#12, but I am not sure about what you mean by rendering the pdf)

Is there any code snippet that does this or what exactly? Sorry for bugging you, but a lil help would be appreciated. :)

**Comment by li-zhenyuan** [comment]
There are two versions of the code. I believe the PDF you mentioned is the result of the archived version, which can be found at this link: https://github.com/li-zhenyuan/Knowledge-enhanced-Attack-Graph/tree/main/Archive-v0.1. The other version in the main folder utilizes matplot as the output method. 
If you want to generate a new version of the PDF, you need to convert the output from JSON format to DOT format. I remember that NetworkX provides a native interface for this purpose.
I hope this clarifies your query.

**Comment by Ema-Ans** [comment]
Yep, thanks!

**Comment by Ema-Ans** [comment]
Hey, I am sorry to bug you again. I am not too sure about how you produce the results, because when I run the code on frankenstein campaign using the following:

```python main.py -M attackGraphGeneration -R "./Dataset/Evaluation/Frankenstein Campaign.txt" -O ./output.pdf ```

This is my output:
![image](https://github.com/li-zhenyuan/Knowledge-enhanced-Attack-Graph/assets/87119440/5980e47d-e078-42ba-88bc-a1423da10579)


I am trying to reproduce the results mentioned in the paper. These ones:
![image](https://github.com/li-zhenyuan/Knowledge-enhanced-Attack-Graph/assets/87119440/c1d468cd-9f10-49ea-a8fa-cd5bb37f225c)

How can I get the entities and get the false positives and negatives after running them on the reports? Also, where can I get the ground truth from for the entities and dependencies?

Thanks in advance!

**Comment by li-zhenyuan** [comment]
For the 1st question, you can make the graph look connected by adjusting the aggregation threshold. For the second one, the ground-truth is labeled manually.
