### ISSUE TITLE
human-labled training data

### ISSUE THREAD

**Issue by jxfis** [li-zhenyuan/Knowledge-enhanced-Attack-Graph#15]
Excuse me.Could you please share the human-labled training data, 20210813.jsonl, for NER model re-training.It will be very appreciated it if you could help.

**Comment by li-zhenyuan** [comment]
I don't want to spend time looking for these archived files, and I've tried, GPT4 works better than any manual annotation.

**Comment by jxfis** [comment]
thank you for your replay




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LI ***@***.***&gt;; 
发送时间: 2023年9月7日(星期四) 下午4:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [li-zhenyuan/Knowledge-enhanced-Attack-Graph] human-labled training data (Issue #15)





 
我不想花时间寻找这些存档文件，我已经尝试过，GPT4 比任何手动注释都好。↳
 
-
 直接回复此电子邮件，在 GitHub 上查看或取消订阅。
您收到此消息是因为您创作了线程。Message ID: ***@***.***&gt;↳
