### ISSUE TITLE
关于Archive v0.1与主工程的差异性

### ISSUE THREAD

**Issue by zhang-xh95** [li-zhenyuan/Knowledge-enhanced-Attack-Graph#2]
您好，打扰了，有几个问题想请教下：
1. Archive V0.1构建的attackGraph与使用主目录工程构建的attackGraph区别很大 例如图的表示，以及Node的内容等
2. techniqueIdentify只有主目录下的工程能跑起来 提供的templates不适用于Archive V0.1下的Identify
3. 利用techniqueIdentify对attack_report示例进行攻击tec识别，和您在attack report analysic(1-8).doc文档中提供的识别tec差距很大

**Comment by li-zhenyuan** [comment]
实验代码，不保证兼容。

**Comment by zhang-xh95** [comment]
那您这边能提供下Archive V0.1 techniqueIdentify的templates么
