### ISSUE TITLE
Control experiment

### ISSUE THREAD

**Issue by cjj1472111531** [li-zhenyuan/Knowledge-enhanced-Attack-Graph#6]
Can you send the TTPDrill code mentioned in the paper and the installation of the dependent send for reference to learn?

**Comment by cjj1472111531** [comment]
To wuxibeilin@qq.com . Thank you very much

**Comment by cjj1472111531** [comment]
Can the author help solve the following? TTPDrill0.5 code and environment for my reference ah, thank the author

**Comment by li-zhenyuan** [comment]
> Can the author help solve the following? TTPDrill0.5 code and environment for my reference ah, thank the author

Search it on search enigne like google or github.

**Comment by cjj1472111531** [comment]
Ttpdrill author in his environment configuration is just a brief description, do not want ATTcAKg so detailed, because you take him as the control group in the paper, I want to understand the environment from you，thank you
