### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by navidaftabi** [li-zhenyuan/Knowledge-enhanced-Attack-Graph#9]
I am trying to install this in a separate environment. There is dependency issue as follow

ERROR: Cannot install -r requirements.txt (line 13), -r requirements.txt (line 4) and numpy==1.22.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.22.3
    blis 0.7.6 depends on numpy>=1.15.0
    coreferee 1.0.1 depends on numpy~=1.19.2

**Comment by li-zhenyuan** [comment]
#3

**Comment by li-zhenyuan** [comment]
You may refer to #3.
